config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # post '/login', to: 'sessions#create'
  # get '/login', to: 'sessions#show'
  # get '/login', to: 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  resources :users
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      login_url @user
      redirect_to user_url @user
    else
      flash.now[:danger] = 'Invalid credentials'
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :surname, :email, :password)
  end

  def create
    @userdbcheck = User.find_by(email: user_params[:email])
    if @userdbcheck == nil
      @user = User.new(user_params)
      @user.save
      redirect_to login_path
    else
      flash.now[:danger] = 'Email has already been taken'
      render 'new'
    end
  end

  def index
    @user = User.find(session[:user_id])
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mymealapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%
=begin%>
 <%= debug(params) if Rails.env.development? %> 
<%
=end%>
  </body>
</html>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_with scope: :user, url: users_path, local: true do |form| %>

        <% if flash[:danger] %>

                <div class="login-notice"><%= flash[:danger] %></div>
                
        <% end %>

        <%= form.label :first_name %><br>
        <%= form.text_field :first_name %>

        <br>

        <%= form.label :surname %><br>
        <%= form.text_field :surname %>

        <br>

        <%= form.label :email %><br>
        <%= form.text_field :email %>

        <br>

        <%= form.label :password %><br>
        <%= form.password_field :password %>

        <br>

        <%= form.submit "Signup", :class => 'btn' %>

<% end %>

app/views/users/show.html.erb
<p> Welcome <%= @user.first_name %> ! </p>